//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataGenMessages_Fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataGenMessages_Fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataGenerator.DataGenMessages_Fr", typeof(DataGenMessages_Fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : Can&apos;t find Enum {2}.
        /// </summary>
        internal static string ATT_ENUM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATT_ENUM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : {1} is a forbidden name.
        /// </summary>
        internal static string ATT_FORBIDDEN_NAME {
            get {
                return ResourceManager.GetString("ATT_FORBIDDEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : {2} value is not expected but &apos;{3}&apos; was found.
        /// </summary>
        internal static string ATT_FOUND {
            get {
                return ResourceManager.GetString("ATT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute without name.
        /// </summary>
        internal static string ATT_NO_NAME {
            get {
                return ResourceManager.GetString("ATT_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : {2} value is expected but not found.
        /// </summary>
        internal static string ATT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : Can&apos;t find the attribute {2} of table {3}.
        /// </summary>
        internal static string ATT_REF_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATT_REF_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : expected the attribute {2} of table {3} to be a reference.
        /// </summary>
        internal static string ATT_REF_NOT_REF {
            get {
                return ResourceManager.GetString("ATT_REF_NOT_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : A Refex can&apos;t reference a struct.
        /// </summary>
        internal static string ATT_REFEX_TO_STRUCT_ERROR {
            get {
                return ResourceManager.GetString("ATT_REFEX_TO_STRUCT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : Can&apos;t find Table {2}.
        /// </summary>
        internal static string ATT_TABLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATT_TABLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : {2} value is unknown type.
        /// </summary>
        internal static string ATT_UNKNOWN_TYPE {
            get {
                return ResourceManager.GetString("ATT_UNKNOWN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : {2} value is unknown.
        /// </summary>
        internal static string ATT_UNKNOWN_VALUE {
            get {
                return ResourceManager.GetString("ATT_UNKNOWN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : {2} value is expected to be an Integer.
        /// </summary>
        internal static string ATT_VAL_NOT_INT {
            get {
                return ResourceManager.GetString("ATT_VAL_NOT_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entity &apos;{0}&apos; doesn&apos;t exists.
        /// </summary>
        internal static string ENTITY_UNKNOWN_TAG {
            get {
                return ResourceManager.GetString("ENTITY_UNKNOWN_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : The name {1} has been found twice.
        /// </summary>
        internal static string ERR_DUPLICATE {
            get {
                return ResourceManager.GetString("ERR_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Attribute {1} : Type {2} and Type {3} are incompatible.
        /// </summary>
        internal static string GEN_REL_TYPES {
            get {
                return ResourceManager.GetString("GEN_REL_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} didn&apos;t expect any tag.
        /// </summary>
        internal static string NO_TAGS_EXPECTED {
            get {
                return ResourceManager.GetString("NO_TAGS_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : Reference of {1} is incomplete.
        /// </summary>
        internal static string NULL_REFERENCE {
            get {
                return ResourceManager.GetString("NULL_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Name is already used.
        /// </summary>
        internal static string TABLE_DUPLICATE_NAME {
            get {
                return ResourceManager.GetString("TABLE_DUPLICATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} is a forbidden name.
        /// </summary>
        internal static string TABLE_FORBIDDEN_NAME {
            get {
                return ResourceManager.GetString("TABLE_FORBIDDEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Musn&apos;t have a Major Tag.
        /// </summary>
        internal static string TABLE_MAJOR_TAG_FOUND {
            get {
                return ResourceManager.GetString("TABLE_MAJOR_TAG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table without Name has been found.
        /// </summary>
        internal static string TABLE_NO_NAME {
            get {
                return ResourceManager.GetString("TABLE_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Can&apos;t find table {1}.
        /// </summary>
        internal static string TABLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TABLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : tag {1} is duplicated.
        /// </summary>
        internal static string TAG_DUPLICATE {
            get {
                return ResourceManager.GetString("TAG_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : tag {2} is forbidden for tables of type {2}.
        /// </summary>
        internal static string TAG_FORBIDDEN {
            get {
                return ResourceManager.GetString("TAG_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table {0} : Section {1} is unknown.
        /// </summary>
        internal static string UNKNOWN_SECTION {
            get {
                return ResourceManager.GetString("UNKNOWN_SECTION", resourceCulture);
            }
        }
    }
}
