//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MightyGmCtrl.Langues {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MightyGmCtrl.Langues.Fr", typeof(Fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;operation a été annulée.
        /// </summary>
        internal static string ABORT {
            get {
                return ResourceManager.GetString("ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ne peux pas convertir la valeur &apos;{0}&apos; en {1}.
        /// </summary>
        internal static string CANT_CONVERT {
            get {
                return ResourceManager.GetString("CANT_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : ne peut pas ouvrir le fichier.
        /// </summary>
        internal static string CANT_OPEN_FILE {
            get {
                return ResourceManager.GetString("CANT_OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un objet DataModel a été trouvé sans nom renseigné pour le type &apos;{0}&apos;.
        /// </summary>
        internal static string DATAMOD_NO_NAME {
            get {
                return ResourceManager.GetString("DATAMOD_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un objet DataModel a été trouvé sans tag renseigné pour le type &apos;{0}&apos;.
        /// </summary>
        internal static string DATAMOD_NO_TAG {
            get {
                return ResourceManager.GetString("DATAMOD_NO_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string EXPORT_PROC {
            get {
                return ResourceManager.GetString("EXPORT_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import : &apos;{0}&apos;.
        /// </summary>
        internal static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : N&apos;a pas trouvé la feuille Excel &apos;{0}&apos;.
        /// </summary>
        internal static string IMPORT_ERROR_NO_SHEET {
            get {
                return ResourceManager.GetString("IMPORT_ERROR_NO_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string IMPORT_PROC {
            get {
                return ResourceManager.GetString("IMPORT_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il faut d&apos;abord sélectionner un type pour pouvoir effectuer cette opération..
        /// </summary>
        internal static string MUST_SELECT_TYPE {
            get {
                return ResourceManager.GetString("MUST_SELECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom &apos;{0}&apos; existe déjà dans la base de donnée pour le type &apos;{1}&apos;..
        /// </summary>
        internal static string NAME_ALREADY_IN_DATABASE {
            get {
                return ResourceManager.GetString("NAME_ALREADY_IN_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} erreurs ont été trouvées..
        /// </summary>
        internal static string NBR_ERROR_FOUND {
            get {
                return ResourceManager.GetString("NBR_ERROR_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le tag &apos;{0}&apos; n&apos;a pas été trouvé pour le type &apos;{1}&apos;..
        /// </summary>
        internal static string NO_TAG {
            get {
                return ResourceManager.GetString("NO_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La fonction n&apos;a pas été implémentée..
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier &apos;{0}&apos; n&apos;a pas été trouvé..
        /// </summary>
        internal static string RESSOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESSOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sommaire.
        /// </summary>
        internal static string SUMMARY {
            get {
                return ResourceManager.GetString("SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un problème est survenu lors de la recherche de la propriété &apos;{0}&apos; de la classe &apos;{1}&apos;..
        /// </summary>
        internal static string TYPE_PROP_NOT_FOUND {
            get {
                return ResourceManager.GetString("TYPE_PROP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La Dll d&apos;extention graphique &apos;{0}&apos; n&apos;a pas été trouvée..
        /// </summary>
        internal static string UI_DLL_NOT_FOUND {
            get {
                return ResourceManager.GetString("UI_DLL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La Dll d&apos;extention graphique &apos;{0}&apos; n&apos;a pas pu être chargée..
        /// </summary>
        internal static string UI_DLL_NOT_LOADED {
            get {
                return ResourceManager.GetString("UI_DLL_NOT_LOADED", resourceCulture);
            }
        }
    }
}
